'''
This question is asked by Google. You are given two strings, s and t which 
only consist of lowercase letters. t is generated by shuffling the letters
in s as well as potentially adding an additional random character. Return the
letter that was randomly added to t if it exists, otherwise, return ’  ‘.
Note: You may assume that at most one additional character can be added to t.

Ex: Given the following strings...

s = "foobar", t = "barfoot", return 't'
s = "ide", t = "idea", return 'a'
s = "coding", t "ingcod", return ''
'''

def spot_the_difference(s, t):
    char_count = {}
    for char in s:
        char_count[char] = char_count.get(char, 0) + 1
    for char in t:
        char_count[char] = char_count.get(char, 0) - 1
        if char_count[char] < 0:
            return char
    return ''

'''
# clever XOR approach
def spot_the_difference(s, t):
    result = 0
    for char in s + t:
        result ^= ord(char)
    if result != 0: 
        return chr(result)
    else:
        return ''
'''


assert spot_the_difference("foobar", "barfoot") == 't'
assert spot_the_difference("ide", "idea") == 'a'
assert spot_the_difference("coding", "ingcod") == ''
